---
# tasks file for intel_optimized_mysql_server_vpc_creation
- name: Download Terraform modules
  ansible.builtin.include_tasks:
    file: download_tf_module.yml

- name: VPC module
  ansible.builtin.include_tasks:
    file: vpc.yml

- name: Optimized Mysql Server
  ansible.builtin.include_tasks:
    file: mysql_server.yml
  when: vpc_id is defined and db_password is defined

- name: Output
  ansible.builtin.include_tasks:
    file: output.yml
  when: mysql_state == "present"