---
-  name: Playbook using the optimized-mysql-server role
   hosts: localhost
   tasks:
     -  name: running a role intel optimized mysql server with ico
        ansible.builtin.import_role:
          name: intel_optimized_mysql_server_ico_by_densify
        vars:
          densify_state: present
          mysql_state: present
          vpc_id : "<yourvpcid>"
          db_password: "<yourpassword>"
          rds_identifier: "my_rds"

