---
-  name: Playbook using the optimized-mysql-server role
   hosts: localhost
   tasks:
     -  name: running a role intel optimized mysql server with ico
        ansible.builtin.import_role:
          name: intel_optimized_mysql_server_ico_by_densify
        vars:
          densify_state: present
          mysql_state: present
          vpc_id : "vpc-091a18706e91c1f55"
          db_password: "Calsoft#123"
          rds_identifier: "demo"

