---
- name: Run intel_optimized_mysql_server_vpc_creation role
  hosts: localhost
  tasks:
    - name: Running a role intel optimized mysql server with vpc creation
      ansible.builtin.import_role:
        name: intel_optimized_mysql_server_vpc_creation
      vars:
        vpc_state: present
        mysql_state: present
        db_password: "<yourpassword>"
        vpc_name: "<yourvpcname>"
        vpc_cidr: "10.0.0.0/16"
        vpc_azs: [ "us-east-2a", "us-east-2b", "us-east-2c" ]
        vpc_private_subnets: [ "10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24" ]
        vpc_tags:
          Owner: "Intel.Cloud.Optimization.Modules@intel.com"
          Duration: "5"
          Company: Intel
        rds_identifier: "mysql-dev-with-vpc1"
        db_multi_az: false
        db_create_subnet_group: true
        db_subnet_group_name: "intel-1-test-db-subnet-group"
        db_tags:
          Owner: "Intel.Cloud.Optimization.Modules@intel.com"
          Duration: "4"
          Company: Intel
        db_ingress_cidr_blocks: [ "10.10.1.0/24" ]