---
- name: Run intel_optimized_mysql_server_expanded role
  hosts: localhost
  tasks:
    - name: Running a role intel optimized mysql server expanded
      ansible.builtin.import_role:
        name: intel_optimized_mysql_server_expanded
      vars:
        mysql_state: present
        db_password: "Passwort!123"
        vpc_id: "vpc-5ea60f23"
        rds_identifier: "mysql-dev-expanded"
#        db_parameters:
#          mysql:
#            innodb_open_files:
#              apply_method: "pending-reboot"
#              value: "4000"